// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _SB_._MediatrixApi_._Infraestructura_.Persistencia;

#nullable disable

namespace _SB_._MediatrixApi_._Infraestructura_.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250204075822_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("_SB_._MediatrixApi_._Dominio_.Entidades.CategoriaEntidad", b =>
                {
                    b.Property<int>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstaEliminado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("CategoriaId");

                    b.ToTable("CategoriasEntidad");
                });

            modelBuilder.Entity("_SB_._MediatrixApi_._Dominio_.Entidades.EntidadGubernamental", b =>
                {
                    b.Property<int>("EntidadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstaEliminado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreEncargado")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Siglas")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("EntidadId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("EntidadesGubernamentales");
                });

            modelBuilder.Entity("_SB_._MediatrixApi_._Dominio_.Entidades.EntidadGubernamental", b =>
                {
                    b.HasOne("_SB_._MediatrixApi_._Dominio_.Entidades.CategoriaEntidad", "Categoria")
                        .WithMany("EntidadesGubernamentales")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("_SB_._MediatrixApi_._Dominio_.Entidades.CategoriaEntidad", b =>
                {
                    b.Navigation("EntidadesGubernamentales");
                });
#pragma warning restore 612, 618
        }
    }
}
